project:
  type: website

website:
  title: "my_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - text: My Resume
        href: materials/resume_may_16_25.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto