project:
  type: website

website:
  title: "Cara's Website"
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto